import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useLaunchesQuery, LaunchesDocument } from '../generated/graphql';
import { initializeApollo } from '../lib/apollo';
import styles from '../styles/Home.module.css';
import Main from '../components/Main';

export default function Home() {
  const { data } = useLaunchesQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ul>
        <Main data={data?.launches} />
      </ul>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const client = initializeApollo();
  await client.query({ query: LaunchesDocument });
  return {
    props: { initialApolloState: client.cache.extract() },
  };
};
