import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useLaunchesQuery, LaunchesDocument } from '../generated/graphql';
import { client } from '../lib/apollo';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { data } = useLaunchesQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ul>
        <h1>{data?.launches.map((i) => i.name)}</h1>
        {/* {data.map((item) => (
          <li key={item.id}>{item.name}</li>
        ))} */}
      </ul>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  await client.query({ query: LaunchesDocument });
  return {
    props: {},
  };
};
